from turtle import *
# Creacion de tortuga (Monse)
Monse=Turtle()
Monse.penup()
Monse.goto(-150,190)
Monse.pendown()
Monse.forward(100)
Monse.right(90)
Monse.forward(200)
Monse.left(45)
Monse.forward(150)